/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmgame_free: (a: number, b: number) => void;
export const rules_json_for_profile: (a: number, b: number, c: number) => void;
export const wasmgame_new: (a: number, b: number, c: number, d: bigint) => void;
export const wasmgame_with_profile: (a: number, b: number, c: number, d: bigint, e: number, f: number) => void;
export const wasmgame_procedural: (a: number, b: number, c: number, d: number, e: bigint, f: number) => void;
export const wasmgame_procedural_with_profile: (a: number, b: number, c: number, d: number, e: bigint, f: number, g: number, h: number) => void;
export const wasmgame_rules_profile: (a: number, b: number) => void;
export const wasmgame_reset: (a: number, b: number) => void;
export const wasmgame_state_json: (a: number, b: number) => void;
export const wasmgame_legal_actions_json: (a: number, b: number) => void;
export const wasmgame_policy_observation_json: (a: number, b: number) => void;
export const wasmgame_step: (a: number, b: number, c: number) => void;
export const wasmgame_step_bot: (a: number, b: number) => void;
export const wasmgame_step_search: (a: number, b: number) => void;
export const wasmgame_step_search_with_budget: (a: number, b: number, c: number) => void;
export const wasmgame_search_node_budget: (a: number) => number;
export const wasmgame_search_nodes: (a: number) => number;
export const wasmgame_search_count: (a: number) => bigint;
export const __wbg_wasmreplay_free: (a: number, b: number) => void;
export const wasmreplay_new: (a: number, b: number, c: number) => void;
export const wasmreplay_frame_count: (a: number) => number;
export const wasmreplay_metadata_json: (a: number, b: number) => void;
export const wasmreplay_seek: (a: number, b: number, c: number) => void;
export const engine_version: () => number;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number, b: number, c: number) => void;
